// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Error(arg1:string):Promise<model.BaseResponse>;

export function Ok(arg1:any):Promise<model.BaseResponse>;

export function OnDownload(arg1:string,arg2:string):Promise<model.BaseResponse>;

export function OnSearch(arg1:string,arg2:number,arg3:number):Promise<model.BaseResponse>;
