// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function OnDownload(arg1:string,arg2:string):Promise<model.BaseResponse>;

export function OnDownloadResult(arg1:model.BaseResponse):void;

export function OnGetSetting():Promise<model.BaseResponse>;

export function OnSearch(arg1:string,arg2:number,arg3:number):Promise<model.BaseResponse>;

export function OnSelectSavePath():Promise<model.BaseResponse>;

export function OnSetSetting(arg1:string):Promise<model.BaseResponse>;
