// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnDownload(arg1, arg2) {
  return window['go']['app']['App']['OnDownload'](arg1, arg2);
}

export function OnDownloadResult(arg1) {
  return window['go']['app']['App']['OnDownloadResult'](arg1);
}

export function OnSearch(arg1, arg2, arg3) {
  return window['go']['app']['App']['OnSearch'](arg1, arg2, arg3);
}
