// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function GenError(arg1:string):Promise<model.BaseResponse>;

export function GenOk(arg1:any):Promise<model.BaseResponse>;

export function GetI18nSource(arg1:string):Promise<model.I18nSourceMap>;

export function GetSetting():Promise<model.Setting>;

export function Log(arg1:string):Promise<void>;

export function OnGetSetting():Promise<model.BaseResponse>;

export function OnSelectSavePath():Promise<model.BaseResponse>;

export function OnSetSetting(arg1:string):Promise<model.BaseResponse>;

export function SetSetting(arg1:model.Setting):Promise<Error>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop(arg1:context.Context):Promise<void>;

export function TR(arg1:string):Promise<string>;
