// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetI18nSource(arg1) {
  return window['go']['app']['AppQQ']['GetI18nSource'](arg1);
}

export function OnDownload(arg1, arg2) {
  return window['go']['app']['AppQQ']['OnDownload'](arg1, arg2);
}

export function OnGetSetting() {
  return window['go']['app']['AppQQ']['OnGetSetting']();
}

export function OnSearch(arg1, arg2, arg3) {
  return window['go']['app']['AppQQ']['OnSearch'](arg1, arg2, arg3);
}

export function OnSelectSavePath() {
  return window['go']['app']['AppQQ']['OnSelectSavePath']();
}

export function OnSetSetting(arg1) {
  return window['go']['app']['AppQQ']['OnSetSetting'](arg1);
}
