// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnDownload(arg1, arg2) {
  return window['go']['kuwo']['AppKuwo']['OnDownload'](arg1, arg2);
}

export function OnSearch(arg1, arg2, arg3) {
  return window['go']['kuwo']['AppKuwo']['OnSearch'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['kuwo']['AppKuwo']['Startup'](arg1);
}

export function Stop(arg1) {
  return window['go']['kuwo']['AppKuwo']['Stop'](arg1);
}
