// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnSearch'](arg1, arg2, arg3);
}

export function Error(arg1) {
  return window['go']['main']['App']['Error'](arg1);
}

export function Ok(arg1) {
  return window['go']['main']['App']['Ok'](arg1);
}

export function OnDownload(arg1, arg2) {
  return window['go']['main']['App']['OnDownload'](arg1, arg2);
}
